### PR TITLE
World map performance improvements

### PR DESCRIPTION
**Pull request by Rahmsauce**
I have made some changes to improve the performance of the world map (#55):

- The world map is now processed asynchronously on the client.
- Plotly, sorttable and fetch-data are loaded in the background resulting in them no longer blocking the rendering of the page.
- Scripts are only loaded on pages which need them (e.g. plotly is no longer loaded on data.html).

These changes contribute to a considerable reduction of loading times on all pages as well as the lighthouse performance score of index.html finally being in the double-digits!

There have also been some small visual changes: First of all, the marker colors look a little different now because I couldn't find a simple way of implementing them the same way as they were before. Furthermore, the layout of the labels which appear when hovering over a marker has been slightly tweaked. If you want, I could try replicating the previous look again. 

Before:
screenshot before

After:
screenshot after

### CODE REVIEW

**Comment by Rahmsauce** [comment]
I gave myself another try to replicate the previous color scale. The result isn't perfect but it is pretty close:

Screenshot_2020-09-04 COVID-19 Dashboard Home

What do you think?

**Comment by BrianRuizy** [comment]
Looks good! @Rahmsauce
Did add those changes to this pr?

**Comment by Rahmsauce** [comment]
Thanks! Yes, I did.

**Review by BrianRuizy — COMMENTED** [review]
approved changes

**Pull request merged**
